name: Sync to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  region: us-east-1
  bucket: simpleitk
jobs:
  sync:
    name: Sync simpleitk bucket
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install awscli -y
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::774096297494:role/cicd-runner-admin
        aws-region: us-east-1
        # role-skip-session-tagging: true
        role-duration-seconds: 3600
    - name: Push MD5 and SHA512 to S3 simpleitk
      run: |
        aws s3 sync . s3://${{ env.bucket }}/public --exclude "*" --include "MD5/*" --include "SHA512/*" --size-only

    - name: Verify ./MD5
      run: |
        find ./MD5 -type f | wc -l
        aws s3 ls --summarize --human-readable --recursive s3://${{ env.bucket }}/public/MD5 | grep Total
        
    - name: Verify ./SHA512
      run: |
        find ./SHA512 -type f | wc -l
        aws s3 ls --summarize --human-readable --recursive s3://${{ env.bucket }}/public/SHA512 | grep Total
